name: Build libfuzzer

on:
  push:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build libfuzzer
      run: mkdir build && cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build
    
    - name: Test a naive target
      run: cd build && (./example || true) && ls | grep crash